name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9829ebc4b8ae2a9f115757f0cb527cb737f23372da9d764fb113ca6e47cb62b4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
