name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "718095b5358449f0cdad2f68a0654b8a37cb8a3881df86e5a03fa18600b11e6d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
