name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e13e59cfbfcdba27b23baa0de1f892f325270cb86bc9cb51dfeccdaf7a4ba67c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
