name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0465f169d84d5b4b8287e940cbc94f65c9fe0a954a34bcc25933ecf7a7cd00e8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
