name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3244c51453e5e82bf858f2f6c0a70827f04b93365d5b74195afd6d171c08577"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
