name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3895f9333c657aea829436d21e8856866a99b5efff04179a77993cd8275dc9d1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
