name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a2b03f0a3d2965ca90ec135fe460cc27dea2c83d890132208a907ef117a1158"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
