name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00334364c2275f009e7dfb77cb462705c451b011568340668c36d4cc00c38c8c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
