name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7edb4927657df5535202f7e7eac586d33ca65ccef526d3dd1e48ad5adf094d9f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
