name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1707161f98120d0445457ef8d38ebf472021bae59f06a910f9e42cba86d6c70"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
