name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b66c51e58c7cc7021b96b420b84a5f23de7ec81d853e8242f2e07475b80c2c33"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
