name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66bdd8811cedd2a9efd1e281715aaf901001734dcf2a5df3501359b1699d5379"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
