name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4313c25b77ac8d20291831388a748cb87a5dc36fc744a1659e3e190b993dceea"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
