name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d0b4dfff6e9256f9b9a60268462dae472e8fc5845d6715e377f93f4bce84122"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
