name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b116813d1ff0f42bcf84c4fa720110b1ce1e603d345306ab48f97a461d77e1b1"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
