name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5f6a1420df1412fd3de833d9dd4ece106802520c25aa88023a9824ab260ab3c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
