name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf7d90eb1239dce4938d4fd743b3b13f4e40b61b0a8161ab047464875dc08f79"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
