name = "Vanilla Patchcraft"
author = "xinchen"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc77884fc45e646feec0fbfa80f96f2c16983b64e32db6cbc2fc562a929b25b8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
